version: "3.7"

services:
  fastapi:
    container_name: application-fastapi
    command: "uvicorn app:app --reload --use-colors --host 0.0.0.0 --port 80"
    build: ./
    environment:
      - DATABASE_URI=postgresql://root:12345@db/crud_fastapi
    ports:
      - 8000:80
    depends_on:
      - db
    links:
      - db:db
    networks:
      - default

  db:
    image: postgres:12-alpine
    container_name: database-postgres
    volumes:
      - /home/docker/volumes/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=crud_fastapi
    ports:
      - 5432:5432
    networks:
      - default
    restart: always
