version: "3"

services:
  fastapi:
    container_name: application-fastapi
    command: "uvicorn app:app --reload --use-colors --host 0.0.0.0 --port 80"
    build: ./
    environment:
      - DATABASE_URI=postgresql://root:12345@postgresql:5432/crud_fastapi
    ports:
      - 8000:80
    links:
      - postgresql
    depends_on:
      - postgresql

  postgresql:
    image: postgres:12-alpine
    container_name: database-postgres
    volumes:
      - ./.data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=crud_fastapi
    ports:
      - 5055:5432
    restart: always
